//LIVENDA CTAA V3.3 2018 CINEMATIC TEMPORAL ANTI ALIASING
//Copyright Livenda Labs 2018
//pc-v3.3


Shader "Hidden/CTAA_PC" {
Properties {
	_MainTex ("Base (RGB)", 2D) = "white" {}
	
}

SubShader {
	ZTest Always Cull Off ZWrite Off Fog { Mode Off }
	Pass {

CGPROGRAM
#pragma target 3.0
#pragma vertex vert
#pragma fragment frag
#pragma fragmentoption ARB_precision_hint_fastest
#pragma glsl
#pragma exclude_renderers d3d11_9x
#include "UnityCG.cginc"

            
float4 _MainTex_TexelSize;
uniform sampler2D _MainTex;
uniform sampler2D _Accum;
uniform sampler2D _Motion0;
uniform sampler2D _CameraDepthTexture;
uniform float _motionDelta;
uniform float _motionDeltaDynamic;
uniform float _AdaptiveResolve;

float4 _ControlParams;
sampler2D_half _CameraMotionVectorsTexture;



float QUODKADLLDLKJWIFWIEI384(float3 Color)
{
	return (Color.g * 2.0) + (Color.r + Color.b);
}

//QIUYAIUFAIWEIUFAYWEIFACFHNIEWUFYIUWEAFHLAIEFCHAIUIFHAUIEWFHAIWIWEHAIUWHFIKFLAWHFN
//HAIWEFUHASJKLDNAEUWHFUIAFHAUIFHAUIHNCFAEFIHAWEUIFHWEIUFHAIUHFAUFLUIAHALUIHALUIWFH
inline float HEUAFEHAFEIOIUE343(float3 Color, float FHTHDGRRRRTEOE) 
{
	return rcp(QUODKADLLDLKJWIFWIEI384(Color) * FHTHDGRRRRTEOE + 4.0);
}

float ISIUFEUHFAEUEFFFFFS343(float3 Color, float FHTHDGRRRRTEOE) 
{
	return rcp(Color.g * FHTHDGRRRRTEOE + 1.0);
}

float ALDSFHKEUAFEUICEUE(float Color, float FHTHDGRRRRTEOE) 
{
	return rcp(Color * FHTHDGRRRRTEOE + 1.0);
}

//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
float UWUHAUEUAFHEIFFA(float Color, float FHTHDGRRRRTEOE) 
{
	return rcp(Color * FHTHDGRRRRTEOE + 4.0);
}

//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
inline float PAOFIEPFAWEUIWHNAIEWUFHAWEIUFH(float3 Color, float FHTHDGRRRRTEOE) 
{
	return 4.0 * rcp(QUODKADLLDLKJWIFWIEI384(Color) * (-FHTHDGRRRRTEOE) + 1.0);
}

float QIUHIIUHIAFIEUH(float3 Color, float FHTHDGRRRRTEOE) 
{
	return rcp(Color.g * (-FHTHDGRRRRTEOE) + 1.0);
}

float OIUFAOEWJAOIEFJOEIWFAAA(float Color, float FHTHDGRRRRTEOE) 
{
	return 4.0 * rcp(Color * (-FHTHDGRRRRTEOE) + 1.0);
}

float OAOIFAEIHUYYYGGHDS(float Color, float FHTHDGRRRRTEOE) 
{
	return rcp(Color * (-FHTHDGRRRRTEOE) + 1.0);
}


float BFBUEAUFAEFAEF(float YURRGASSGBXRTEOE, float FHTHDGRRRRTEOE) 
{
	return YURRGASSGBXRTEOE * OIUFAOEWJAOIEFJOEIWFAAA(YURRGASSGBXRTEOE, FHTHDGRRRRTEOE);
}


float IIAUEUYAFUEYFF(float YURRGASSGBXRTEOE, float FHTHDGRRRRTEOE) 
{
	return YURRGASSGBXRTEOE * OAOIFAEIHUYYYGGHDS(YURRGASSGBXRTEOE, FHTHDGRRRRTEOE);
}


float AFAEJKAEHUIEFEESSE(float3 Color, float FHTHDGRRRRTEOE) 
{
	float L = QUODKADLLDLKJWIFWIEI384(Color);
	return L * UWUHAUEUAFHEIFFA(L, FHTHDGRRRRTEOE);
}

float PWERDFUAEOAIEUH(float3 Color, float FHTHDGRRRRTEOE) 
{
	return Color.g * ALDSFHKEUAFEUICEUE(Color.g, FHTHDGRRRRTEOE);
}

float LUMTAYDFHEUAJHF(float3 Color) 
{
	#if 1
		
		return dot(Color, float3(0.299, 0.587, 0.114));
	#else
		
		return dot(Color, float3(0.2126, 0.7152, 0.0722));
	#endif
}

float OIUOAIWJHISHSS(float YURRGASSGBXRTEOE) 
{
	return YURRGASSGBXRTEOE * rcp(1.0 + YURRGASSGBXRTEOE);
}
	
float DECOMFEOIJOAFEFDD(float YURRGASSGBXRTEOE) 
{
	return YURRGASSGBXRTEOE * rcp(1.0 - YURRGASSGBXRTEOE);
}

float PWERFAFEAFKYHE(float3 Color, float FHTHDGRRRRTEOE) 
{
	return sqrt(OIUOAIWJHISHSS(LUMTAYDFHEUAJHF(Color) * FHTHDGRRRRTEOE));
}

float OOAKLIENAKDHUE(float YURRGASSGBXRTEOE) 
{
	return DECOMFEOIJOAFEFDD(YURRGASSGBXRTEOE * YURRGASSGBXRTEOE);
}
//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
inline float AUUUAWEFNNADUHDDS(float3 Dir, float3 Org, float3 Box)
{
	
	float3 RcpDir = rcp(Dir);
	float3 TNeg = (  Box  - Org) * RcpDir;
	float3 TPos = ((-Box) - Org) * RcpDir;
	return max(max(min(TNeg.x, TPos.x), min(TNeg.y, TPos.y)), min(TNeg.z, TPos.z));
}
//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
inline float HISFEFIAFEIUEHIHAFU(float3 History, float3 FEUAIUAEHDNFCRERESED, float3 HJHUHUEREWERS, float3 AFLFMAAFETHESER)
{
	float3 Min = min(FEUAIUAEHDNFCRERESED, min(HJHUHUEREWERS, AFLFMAAFETHESER));
	float3 Max = max(FEUAIUAEHDNFCRERESED, max(HJHUHUEREWERS, AFLFMAAFETHESER));	
	float3 Avg2 = Max + Min;
	float3 Dir = FEUAIUAEHDNFCRERESED - History;
	float3 Org = History - Avg2 * 0.5;
	float3 Scale = Max - Avg2 * 0.5;
	return saturate(AUUUAWEFNNADUHDDS(Dir, Org, Scale));	
}
//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
float UEAFDJHFEU(float3 Color, float FHTHDGRRRRTEOE) 
{
	return rcp(max(LUMTAYDFHEUAJHF(Color) * FHTHDGRRRRTEOE, 1.0));
}
//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
float4 LERADFHIEUUEDHHD(float4 ColorA, float4 ColorB, float Blend, float FHTHDGRRRRTEOE) 
{
	float BlendA = (1.0 - Blend) * UEAFDJHFEU(ColorA.rgb, FHTHDGRRRRTEOE);
	float BlendB =        Blend  * UEAFDJHFEU(ColorB.rgb, FHTHDGRRRRTEOE);
	float RcpBlend = rcp(BlendA + BlendB);
	BlendA *= RcpBlend;
	BlendB *= RcpBlend;
	return ColorA * BlendA + ColorB * BlendB;
}
//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE


struct v2f {
	float4 pos : POSITION;
	float2 uv : TEXCOORD0;
};

v2f vert( appdata_img v )
{
	v2f o;
	o.pos = UnityObjectToClipPos (v.vertex);
	o.uv = v.texcoord.xy;

	/*
	#if UNITY_UV_STARTS_AT_TOP
		o.uv = v.texcoord.xy;
		if (_MainTex_TexelSize.y < 0)
			o.uv.y = 1-o.uv.y;
		#endif		
		*/

	return o;
}

float4 frag (v2f i) : COLOR
{


//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
// ------------------------------------------------

 float2 LBABKDFHIEAKFJHJDJ;
 float2 FAHEIAIUFHEIFHAKFUIAE;
		
 float  IAFNAEFUAIFUHEUAXXS = 1;
  
 float2  TEDSUIHFDDDSS = _MainTex_TexelSize.xy;

 //WEFUIAHEIAUF AF HAIEHF IAUEFHILAF NAIHFUIAHEFUIAHOFU F AHFIEF AIUFH AIEUFHA IFAUIEFHIUHHAI FAFH IUEFH
 //###################################################

 /*

 float AKFDHIEAUHUDFHAIEU = 1-Linear01Depth(tex2D (_CameraDepthTexture, i.uv).x);
 
 float CHIKAISUZEUFHHFUU = 0.1;
 float2 AFEIHIAUEFHIUNFAIEUEXXFE[4];
 
 AFEIHIAUEFHIUNFAIEUEXXFE[0] = float2( -TEDSUIHFDDDSS.x, -TEDSUIHFDDDSS.y )*CHIKAISUZEUFHHFUU;
 AFEIHIAUEFHIUNFAIEUEXXFE[1] = float2(  TEDSUIHFDDDSS.x, -TEDSUIHFDDDSS.y )*CHIKAISUZEUFHHFUU;
 AFEIHIAUEFHIUNFAIEUEXXFE[2] = float2( -TEDSUIHFDDDSS.x,  TEDSUIHFDDDSS.y )*CHIKAISUZEUFHHFUU;
 AFEIHIAUEFHIUNFAIEUEXXFE[3] = float2(  TEDSUIHFDDDSS.x,  TEDSUIHFDDDSS.y )*CHIKAISUZEUFHHFUU;
 
 float DFJEOAOOOIDFJ[4];
 DFJEOAOOOIDFJ[0] = 1-Linear01Depth(tex2D (_CameraDepthTexture, i.uv + AFEIHIAUEFHIUNFAIEUEXXFE[0] ).x);
 DFJEOAOOOIDFJ[1] = 1-Linear01Depth(tex2D (_CameraDepthTexture, i.uv + AFEIHIAUEFHIUNFAIEUEXXFE[1] ).x);
 DFJEOAOOOIDFJ[2] = 1-Linear01Depth(tex2D (_CameraDepthTexture, i.uv + AFEIHIAUEFHIUNFAIEUEXXFE[2] ).x);
 DFJEOAOOOIDFJ[3] = 1-Linear01Depth(tex2D (_CameraDepthTexture, i.uv + AFEIHIAUEFHIUNFAIEUEXXFE[3] ).x);
 
 int dIndx0;
 if(DFJEOAOOOIDFJ[0] > DFJEOAOOOIDFJ[1]) dIndx0 = 0;
 else dIndx0 = 1;
 
 int dIndx1;
 if(DFJEOAOOOIDFJ[2] > DFJEOAOOOIDFJ[3]) dIndx1 = 2;
 else dIndx1 = 3;
 
 int dIndx2;
 if(DFJEOAOOOIDFJ[dIndx0] > DFJEOAOOOIDFJ[dIndx1]) dIndx2 = dIndx0;
 else dIndx2 = dIndx1;
 
 //-----------------------------------
 int dIndx0C;
 if(DFJEOAOOOIDFJ[0] < DFJEOAOOOIDFJ[1]) dIndx0C = 0;
 else dIndx0C = 1;
 
 int dIndx1C;
 if(DFJEOAOOOIDFJ[2] < DFJEOAOOOIDFJ[3]) dIndx1C = 2;
 else dIndx1C = 3;
 
 int dIndx2C;
 if(DFJEOAOOOIDFJ[dIndx0C] < DFJEOAOOOIDFJ[dIndx1C]) dIndx2C = dIndx0C;
 else dIndx2C = dIndx1C;
 
 //-----------------------------------

 float2 MFOAEIJAFEOEIFHAEUIHUIFAH = float2(0,0);
 
 if( DFJEOAOOOIDFJ[dIndx2] > AKFDHIEAUHUDFHAIEU)
 {
 	MFOAEIJAFEOEIFHAEUIHUIFAH = AFEIHIAUEFHIUNFAIEUEXXFE[dIndx2];
 }

 */

 //###################################################
 //AFEIUHI AHFI UAEFHI FAH UIHNF IAUHFAIU EHAF HIUFH
 half2 FAEHIUHAIFUHAIFNEUFHA = tex2D(_CameraMotionVectorsTexture, i.uv ).rg;
 LBABKDFHIEAKFJHJDJ =   FAEHIUHAIFUHAIFNEUFHA;
 //###################################################

 float EFUIAHIHAFIEIFUHAIFEFF = 2;
 float BBFAIUHIUEFHAFKUUYE = saturate(abs(LBABKDFHIEAKFJHJDJ.x) * EFUIAHIHAFIEIFUHAIFEFF + abs(LBABKDFHIEAKFJHJDJ.y) * EFUIAHIHAFIEIFUHAIFEFF); 	
	half2  uv = i.uv ;					
	half4 AFHIEHIUEHFIUHIFASSAAE = tex2D(_MainTex, uv.xy - TEDSUIHFDDDSS );
	half4 XCCIOFEIFJOEISSD = tex2D(_MainTex, uv.xy + float2(  0, -TEDSUIHFDDDSS.y ) );
	half4 OPEFOAIIEIINNDDS = tex2D(_MainTex, uv.xy + float2(  TEDSUIHFDDDSS.x, -TEDSUIHFDDDSS.y ) );
	half4 DOALJJFOAIIIFJSIQW = tex2D(_MainTex, uv.xy + float2(  -TEDSUIHFDDDSS.x, 0 ) );
	half4 KFAUEYHJDJUAUUUAU = tex2D(_MainTex, uv.xy);
	half4 NEIAFUEHFAFUUEFHA = tex2D(_MainTex, uv.xy + float2(   TEDSUIHFDDDSS.x, 0 ) );
	half4 NNDUUUDDSWWS = tex2D(_MainTex, uv.xy + float2( -TEDSUIHFDDDSS.x,  TEDSUIHFDDDSS.y ) );
	half4 FEUIHAFUEHIAUEFHUHDUA = tex2D(_MainTex, uv.xy + float2(  0,  TEDSUIHFDDDSS.y ) );
	half4 VVDYTTYFETVFY = tex2D(_MainTex, uv.xy + TEDSUIHFDDDSS );

//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE

		//TEDSUIHFDDDSS.xy *=2;

        half ACCDYDHDUDUD = (LUMTAYDFHEUAJHF(tex2D(_MainTex, uv.xy +  float2(  0, -TEDSUIHFDDDSS.y  ) )) );
        half OOACCDFUIEF = (LUMTAYDFHEUAJHF( tex2D(_MainTex, uv.xy + float2(  0,  TEDSUIHFDDDSS.y  ) )) );
        half UEFYBNBNSDDFE = (LUMTAYDFHEUAJHF(tex2D(_MainTex, uv.xy  + float2(  TEDSUIHFDDDSS.x , 0  ) )) );
        half WERESEWRFFE = (LUMTAYDFHEUAJHF(tex2D(_MainTex, uv.xy  + float2( -TEDSUIHFDDDSS.x , 0  ) )) );


        half HAHAFHEHAFUEUEQ = (LUMTAYDFHEUAJHF(tex2D(_MainTex, uv.xy))) - (ACCDYDHDUDUD + OOACCDFUIEF + UEFYBNBNSDDFE + WERESEWRFFE)*0.25;


        half GRADFIEFIJIFESS       = saturate(abs(HAHAFHEHAFUEUEQ));
        GRADFIEFIJIFESS = saturate(pow(GRADFIEFIJIFESS, 4.0)*0.5);

        IAFNAEFUAIFUHEUAXXS = lerp(2.5,12,GRADFIEFIJIFESS)*(0.1*_ControlParams.w);
        		
		AFHIEHIUEHFIUHIFASSAAE.rgb *= HEUAFEHAFEIOIUE343(AFHIEHIUEHFIUHIFASSAAE.rgb, IAFNAEFUAIFUHEUAXXS);
		XCCIOFEIFJOEISSD.rgb *= HEUAFEHAFEIOIUE343(XCCIOFEIFJOEISSD.rgb, IAFNAEFUAIFUHEUAXXS);
		OPEFOAIIEIINNDDS.rgb *= HEUAFEHAFEIOIUE343(OPEFOAIIEIINNDDS.rgb, IAFNAEFUAIFUHEUAXXS);
		DOALJJFOAIIIFJSIQW.rgb *= HEUAFEHAFEIOIUE343(DOALJJFOAIIIFJSIQW.rgb, IAFNAEFUAIFUHEUAXXS);
		KFAUEYHJDJUAUUUAU.rgb *= HEUAFEHAFEIOIUE343(KFAUEYHJDJUAUUUAU.rgb, IAFNAEFUAIFUHEUAXXS);
		NEIAFUEHFAFUUEFHA.rgb *= HEUAFEHAFEIOIUE343(NEIAFUEHFAFUUEFHA.rgb, IAFNAEFUAIFUHEUAXXS);
		NNDUUUDDSWWS.rgb *= HEUAFEHAFEIOIUE343(NNDUUUDDSWWS.rgb, IAFNAEFUAIFUHEUAXXS);
		FEUIHAFUEHIAUEFHUHDUA.rgb *= HEUAFEHAFEIOIUE343(FEUIHAFUEHIAUEFHUHDUA.rgb, IAFNAEFUAIFUHEUAXXS);
		VVDYTTYFETVFY.rgb *= HEUAFEHAFEIOIUE343(VVDYTTYFETVFY.rgb, IAFNAEFUAIFUHEUAXXS);

//AFKKAEHIAUWE AH IEFAIEF AE IHBAF AFUIEF
//OEQWIUOAFOAEWFJASDLHAFEIWLUHAWIFHALIFHAEWIUHAEWIFHLAIUFHAIUWEF
//AWEIIUEILUAAFAIEUFHAIFABCAIUHLEUIFHALUIEFHAIUCFLEIWUFHAUIEHFAIWEFHAEWIHALEWIUHAIWUEHAWIUEHAUIWEHEUEEAWW
//WIEUFHAWEUILAIFA  AFEHIUYHA FAFI UAEHFIUA HFAHE IUAH FAIUFHLAI EFA FLUIAHEFLUIHAELFAWE F  HFAIE AF AFIE
			
		half4 FEUAIUAEHDNFCRERESED= 
			AFHIEHIUEHFIUHIFASSAAE * 0.0625 + 
			XCCIOFEIFJOEISSD * 0.125 +
			OPEFOAIIEIINNDDS * 0.0625 +
			DOALJJFOAIIIFJSIQW * 0.125 +
			KFAUEYHJDJUAUUUAU * 0.25 +
			NEIAFUEHFAFUUEFHA * 0.125 +
			NNDUUUDDSWWS * 0.0625 +
			FEUIHAFUEHIAUEFHUHDUA * 0.125 +
			VVDYTTYFETVFY * 0.0625;
				
			
		float4	 JFEIAFJIJEFIAAS = FEUAIUAEHDNFCRERESED;
		half4 MIFNIEJHAFIAJFA = min(min(AFHIEHIUEHFIUHIFASSAAE, OPEFOAIIEIINNDDS), min(NNDUUUDDSWWS, VVDYTTYFETVFY));		
		half4 NFEIAFINIAFEQW = max(max(AFHIEHIUEHFIUHIFASSAAE, OPEFOAIIEIINNDDS), max(NNDUUUDDSWWS, VVDYTTYFETVFY));		
		half4 HJHUHUEREWERS = min(min(min(XCCIOFEIFJOEISSD, DOALJJFOAIIIFJSIQW), min(KFAUEYHJDJUAUUUAU, NEIAFUEHFAFUUEFHA)), FEUIHAFUEHIAUEFHUHDUA);		
		half4 AFLFMAAFETHESER = max(max(max(XCCIOFEIFJOEISSD, DOALJJFOAIIIFJSIQW), max(KFAUEYHJDJUAUUUAU, NEIAFUEHFAFUUEFHA)), FEUIHAFUEHIAUEFHUHDUA);		
		MIFNIEJHAFIAJFA = min(MIFNIEJHAFIAJFA, HJHUHUEREWERS);
		NFEIAFINIAFEQW = max(NFEIAFINIAFEQW, AFLFMAAFETHESER);
	    HJHUHUEREWERS = HJHUHUEREWERS * 0.5 + MIFNIEJHAFIAJFA * 0.5;
		AFLFMAAFETHESER = AFLFMAAFETHESER * 0.5 + NFEIAFINIAFEQW * 0.5;		
		
	    //AFJEOIFJAOIEJFAOEIJAOEWIFAOEWIFJAOEWIF OAFJ JFAEIUHAFI UH AFHIUFH
	    //AFJEOIFJAOIEJFAOEIJAOEWIFAOEWIFJAOEWIF OAFJ JFAEIUHAFI UH AFHIUFH
	    //AFJEOIFJAOIEJFAOEIJAOEWIFAOEWIFJAOEWIF OAFJ JFAEIUHAFI UH AFHIUFH
	    //AFJEOIFJAOIEJFAOEIJAOEWIFAOEWIFJAOEWIF OAFJ JFAEIUHAFI UH AFHIUFH

	    float4 OUTHJFAEUUHAFUHEEFA = tex2D(_Accum, i.uv-LBABKDFHIEAKFJHJDJ);		
	
	    OUTHJFAEUUHAFUHEEFA.rgb *= HEUAFEHAFEIOIUE343(OUTHJFAEUUHAFUHEEFA.rgb, IAFNAEFUAIFUHEUAXXS);		
		
		float NUMAFJHEIOFHUASTT = QUODKADLLDLKJWIFWIEI384(HJHUHUEREWERS.rgb);
		float BUYUYAFHEFUHFEF = QUODKADLLDLKJWIFWIEI384(AFLFMAAFETHESER.rgb);
		float BUHFUYBUADFH = QUODKADLLDLKJWIFWIEI384(OUTHJFAEUUHAFUHEEFA.rgb);

		float HUNJHAFHURAST = BUYUYAFHEFUHFEF - NUMAFJHEIOFHUASTT;
		float CMNDJBKENBDFS = HISFEFIAFEIUEHIHAFU(OUTHJFAEUUHAFUHEEFA.rgb, JFEIAFJIJEFIAAS.rgb, HJHUHUEREWERS.rgb, AFLFMAAFETHESER.rgb);

		OUTHJFAEUUHAFUHEEFA.rgb = lerp(OUTHJFAEUUHAFUHEEFA.rgb, JFEIAFJIJEFIAAS.rgb, CMNDJBKENBDFS );		

		float YUFEYUYFEUAHFEUYE = saturate(BBFAIUHIUEFHAFKUUYE) * 0.5;
		float HFUNDUCONTGA =  _ControlParams.z;
		
		YUFEYUYFEUAHFEUYE = saturate(YUFEYUYFEUAHFEUYE + rcp(1.0 + HUNJHAFHURAST * HFUNDUCONTGA));
		FEUAIUAEHDNFCRERESED.rgb = lerp(FEUAIUAEHDNFCRERESED.rgb, KFAUEYHJDJUAUUUAU.rgb, YUFEYUYFEUAHFEUYE);


		float vdelta =  saturate(8*length(LBABKDFHIEAKFJHJDJ));
		float sdelta = lerp(17,_ControlParams.y,vdelta);
		_ControlParams.y = lerp(_ControlParams.y , sdelta, _ControlParams.x);
		
		float HFAKYEFUIHFAIUHEIUYHF = (1.0/_ControlParams.y) + BBFAIUHIUEFHAFKUUYE * (1.0/_ControlParams.y);
		float UIUAFEIUIUIUFAE = BUHFUYBUADFH * HFAKYEFUIHFAIUHEIUYHF * (1.0 + BBFAIUHIUEFHAFKUUYE * HFAKYEFUIHFAIUHEIUYHF * 4.0);
		float BLFNDJFHEUFINS = saturate(UIUAFEIUIUIUFAE * rcp(BUHFUYBUADFH + HUNJHAFHURAST));
			
			
		float FINBFIEJIFJJJ = lerp(BLFNDJFHEUFINS, (sqrt(BLFNDJFHEUFINS)), saturate(length(LBABKDFHIEAKFJHJDJ)*_AdaptiveResolve) );
			
		OUTHJFAEUUHAFUHEEFA = lerp(OUTHJFAEUUHAFUHEEFA, FEUAIUAEHDNFCRERESED, FINBFIEJIFJJJ);
		OUTHJFAEUUHAFUHEEFA.rgb *= PAOFIEPFAWEUIWHNAIEWUFHAWEIUFH(OUTHJFAEUUHAFUHEEFA.rgb, IAFNAEFUAIFUHEUAXXS);
			
		OUTHJFAEUUHAFUHEEFA.rgb = -min(-OUTHJFAEUUHAFUHEEFA.rgb, 0.0);

	 	return OUTHJFAEUUHAFUHEEFA;
	 		
}
ENDCG
	}
}

Fallback off

}